### ISSUE TITLE
allow greload to add and remove servers

### ISSUE THREAD

**Issue by PhanaticD** [WaterfallMC/Waterfall-Old#17]
You cannot add or remove servers from the config then use greload without issues

for example after removing lobby from a default config

```
12:36:45 [INFO] An internal error occurred whilst executing this command, please check the console log for details.
12:36:45 [WARNING] Error in dispatching command
java.lang.IllegalArgumentException: Server lobby removed on reload!
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at net.md_5.bungee.conf.Configuration.load(Configuration.java:103)
    at net.md_5.bungee.command.CommandReload.execute(CommandReload.java:20)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by Techcable** [comment]
Oh, there is a bungee PR for removing servers.
SpigotMC/BungeeCord#1019
@PhanaticD 
Does adding servers in reload work?

**Comment by PhanaticD** [comment]
I didnt see any error messages when adding servers, I am not sure if it functionally works though

**Comment by minecrafter** [comment]
Adding servers in the current /greload implementation does work, but changing the address or removing a server isn't allowed.
