### ISSUE TITLE
Disconnects with VarInt too big

### ISSUE THREAD

**Issue by Mxchael** [WaterfallMC/Waterfall-Old#21]
```
java.lang.RuntimeException: VarInt too big
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:117)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:101)
    at net.md_5.bungee.entitymap.EntityMap_1_8.rewriteClientbound(EntityMap_1_8.java:140)
    at net.md_5.bungee.entitymap.EntityMap_1_8.rewriteInternal(EntityMap_1_8.java:55)
    at net.md_5.bungee.entitymap.EntityMap.rewrite(EntityMap.java:106)
    at net.md_5.bungee.entitymap.EntityMap.rewriteClientbound(EntityMap.java:69)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:97)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:84)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by minecrafter** [comment]
Can you give us some details about your server setup?

**Comment by Mxchael** [comment]
Server is Debian running Java 8.

Running PaperSpigot latest on back. VarInt issue happens when no plugins are installed on Waterfall. I have tried to run Waterfall connecting to a default PaperSpigot setup with only changes are to allow Bungeecord and set online mode false. No plugins and I get this. Also running Mark2 as server wrapper.

```
22:10:01 [SEVERE] [Vertalli] <-> DownstreamBridge <-> [TestServer] - encountered exception
java.lang.IndexOutOfBoundsException: readerIndex(5) + length(1) exceeds writerIndex(5): PooledUnsafeDirectByteBuf(ridx: 5, widx: 5, cap: 5)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1178)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:587)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:111)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:101)
    at net.md_5.bungee.entitymap.EntityMap.rewriteVarInt(EntityMap.java:88)
    at net.md_5.bungee.entitymap.EntityMap_1_8.rewriteClientbound(EntityMap_1_8.java:77)
    at net.md_5.bungee.entitymap.EntityMap_1_8.rewriteInternal(EntityMap_1_8.java:55)
    at net.md_5.bungee.entitymap.EntityMap.rewrite(EntityMap.java:106)
    at net.md_5.bungee.entitymap.EntityMap.rewriteClientbound(EntityMap.java:69)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:97)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:84)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
22:10:01 [INFO] [Skull] disconnected with: §fIndexOutOfBoundsException : readerIndex(5) + length(1) exceeds writerIndex(5): PooledUnsafeDirectByteBuf(ridx: 5, widx: 5, cap: 5) @ io.netty.buffer.AbstractByteBuf:1178
22:10:01 [INFO] [Vertalli] disconnected with: §fIndexOutOfBoundsException : readerIndex(5) + length(1) exceeds writerIndex(5): PooledUnsafeDirectByteBuf(ridx: 5, widx: 5, cap: 5) @ io.netty.buffer.AbstractByteBuf:1178
```

Client side is running

[12:17:02] [Client thread/INFO]: LWJGL Version: 2.9.2
[OptiFine] 
[OptiFine] OptiFine_1.8_HD_U_D1
[OptiFine] Sun Jan 31 12:17:03 NZDT 2016
[OptiFine] OS: Mac OS X (x86_64) version 10.11.3
[OptiFine] Java: 1.8.0_60, Oracle Corporation
[OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[OptiFine] LWJGL: 2.9.2
[OptiFine] OpenGL: Intel(R) Iris(TM) Graphics 6100, version 2.1 INTEL-10.12.13, Intel Inc.
[OptiFine] OpenGL Version: 2.1

**Comment by minecrafter** [comment]
There's an [upstream bug](https://github.com/SpigotMC/BungeeCord/issues/1717) for this.

Unfortunately, I don't see a good way to reproduce this issue.

**Comment by Mxchael** [comment]
I cannot reproduce this error using the same setup as Waterfall but replacing waterfall with Bungeecord. This issue is only occurring for me on Waterfall. I can send the files off the Waterfall setup and the server setup if helps with reproducing.

**Comment by minecrafter** [comment]
Oh, so this isn't an upstream bug. Investigating now.

**Comment by minecrafter** [comment]
Can you try https://ci.getwaterfall.xyz/repository/download/Waterfall_Build/250:id/waterfall.jar?

**Comment by Techcable** [comment]
@minecrafter 
I think the issue is that `rewriteInternal()` doesn't reset the packet with `packet.readerIndex(readerIndex);`
The `EntityMap_1_8.rewriteClientbound` method expects the reader index to be reset.

I'm not sure its safe to revert the commit, as I'm relying on that to fix the forge issue.

**Comment by minecrafter** [comment]
Good point @Techcable. You're free to contribute a fix, this was the simplest one I could come up with though.

**Comment by Mxchael** [comment]
Can confirm that fix works @minecrafter

**Comment by minecrafter** [comment]
Thanks @Spurlex.

@Techcable I verified that Forge 1.7.10 still works fine under this commit.
