### ISSUE TITLE
IllegalStateException: Not expecting PING

### ISSUE THREAD

**Issue by mibby** [WaterfallMC/Waterfall-Old#23]
As Waterfall seems to have picked up BungeeCord development, any plans on a workaround fix for this error spam?

Using Waterfall dev 70.

```
00:32:16 [SEVERE] [/75.126.137.90:60269] <-> InitialHandler - encountered exception
java.lang.IllegalStateException: Not expecting PING
    at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
    at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:250)
    at net.md_5.bungee.protocol.packet.PingPacket.handle(PingPacket.java:35)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Techcable** [comment]
What version of the client and server are you using?

**Comment by mibby** [comment]
I'm on MC 1.8 using Waterfall dev 70 and PaperSpigot dev 411. But this is a longstanding BungeeCord issue / error that spams very frequently.

https://github.com/SpigotMC/BungeeCord/issues/1633
https://github.com/SpigotMC/BungeeCord/issues/1544
https://github.com/SpigotMC/BungeeCord/issues/1536

**Comment by Techcable** [comment]
This means someone is sending you invalid data.
I don't understand why you would wan't us to 'fix' a client sending you invalid data.

**Comment by mibby** [comment]
Well I believe it is caused by a server list pinging the server routinely, not from a specific user/client. MinecraftForums server list would be my guess. A 'fix' to clean up the error outputted or prevent it would be nice, since it spams the logs and console window frequently.

**Comment by Techcable** [comment]
Yes, but this is not a valid set of pings.
They have to request status before they ping.

We could change it to allow a ping before a status, even though it is technically invalid.

**Comment by mibby** [comment]
Perhaps it is not a valid ping, but it is the fault of whatever service is pinging the BungeeCord instance via their method used. I assume they wouldn't care whether or not it is causing an error / output to occur. So because it is beyond the control of most BungeeCord users, shouldn't the error be suppressed or have an exception catch with a nicer output or something?

**Comment by Mxchael** [comment]
I agree with suppressing the error. Its just something pinging the server with invalid data and can be very annoying in the logs. It doesn't matter if the ping fails because not valid it would just be nice to get rid of the error.

**Comment by Techcable** [comment]
You can set the property '-Dwaterfall.acceptInvalidPackets=true' at the command line to accept the invalid packets.

**Comment by mibby** [comment]
Are there any downsides to accepting the invalid packets?

**Comment by Techcable** [comment]
@mibby 
It may cause bugs.
I dont think it would in the current implementation though.
