### ISSUE TITLE
Player with ForgeMod can't join the server

### ISSUE THREAD

**Issue by Malachiel87** [WaterfallMC/Waterfall-Old#34]
Not sure what if is a bungeecord issue or waterfall issue but after the update when i join the server with forgemod client it cause this error and i can't join the server

01:42:38 [INFORMAZIONI] [BungeePerms] Login by Malachiel>
01:42:38 [GRAVE] feb 19, 2016 1:42:38 AM io.netty.util.concurrent.SingleThreadEventExecutor runAllTasksAVVERTENZA: A task raised an exception.
java.lang.NullPointerException    at net.md_5.bungee.UserConnection.init(UserConnection.java:189)    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:503)    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:259)    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)    at java.lang.Thread.run(Thread.java:745)>

**Comment by minecrafter** [comment]
What Bungee plugins are you running?

**Comment by Malachiel87** [comment]
BungeeAuth
DuckSuite (gesuite)
SkinsRestorer
Ultimate Friends
Simple Hub Command
PlayerServer
BungeePerms

**Comment by minecrafter** [comment]
Try removing SkinRestorer

**Comment by Malachiel87** [comment]
i tried to use bungeecord, work perfect, is a waterfall issue

**Comment by Malachiel87** [comment]
tried to remove skinsrestorer is the same, got the same error

**Comment by jiongjionger** [comment]
I have same issue (https://github.com/WaterfallMC/Waterfall/issues/30)

**Comment by kashike** [comment]
I'm unable to reproduce this with the latest Waterfall and Forge builds - can you provide a list of BungeeCord/Waterfall plugins, and a stacktrace that you get?

**Comment by RhvsW** [comment]
Also unable to produce this with the latest Waterfall & Forge builds, 

Minecraft 1.8.9, MCP 9.19, Powered by Forge 11.15.1.1761, 3 mods loaded, 3 mods active
https://cd0.us/files/f722981ad2c894783dc7e73f81be4cd1.png

This server is running Waterfall version git:Waterfall-Bootstrap:1.8-SNAPSHOT:5b01f9f:107 by the Waterfall team

Waterfall plugins in use:
- AlwaysOnline - latest
- BungeeServerManager - latest
- ServerListPlus - latest
- SlashServer -latest

**Comment by Techcable** [comment]
Try to remove plugins one by one until you identify the issue.
Then we may be able to which plugin triggers the error.

**Comment by ghost** [comment]
Just switched over to Waterfall, this issue doesn't happen with me.

**Comment by minecrafter** [comment]
Closing due to inactivity
