### ISSUE TITLE
Compressed packet size mismatch

### ISSUE THREAD

**Issue by mibby** [WaterfallMC/Waterfall-Old#40]
@minecrafter @Techcable 
WaterFall dev 142. Error occurs when players try to connect.

```
02:44:15 [SEVERE] [/IP:PORT|player] <-> DownstreamBridge <-> [Server] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Compressed packet size mismatch
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Compressed packet size mismatch
    at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
    at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:38)
    at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:11)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    ... 15 more
```

Downgrading to WaterFall dev 141, everything is fine.

**Comment by Janmm14** [comment]
@mibby are you sure thats legitimate traffic?

**Comment by mibby** [comment]
@Janmm14 Should be. Was the same players reconnecting after I updated. They couldn't get back on. I even got the same error trying to connect to my server on WaterFall 142. Downgrading to 141, all is good.

**Comment by Janmm14** [comment]
@mibby I think #142 is broken.

**Comment by Techcable** [comment]
Reopen this if it doesn't fix it.

**Comment by mibby** [comment]
@Techcable On dev 143. Started out fine, users could connect. Then disconnection with error happened. Downgrading back to dev 141 in the meantime.

```
03:24:50 [SEVERE] [/IP|player] <-> DownstreamBridge <-> [Server] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Decompressed size 284 is less than compressed bytes [295]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Decompressed size 284 is less than compressed bytes [295]
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:42)
    at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:13)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    ... 15 more
```

**Comment by Janmm14** [comment]
https://github.com/WaterfallMC/Waterfall/commit/ad37f28cdc55672ab3ebeb3897461052a549bb36#commitcomment-16772707

Can't sometimes the compression add unneccessary overhead especially if the packet which was compressed is not that big?

**Comment by minecrafter** [comment]
I've removed the check in 93a91ad. The remaining check will help stop DarkBot and other invalid packets.
