### ISSUE TITLE
UnknownHostException

### ISSUE THREAD

**Issue by mibby** [WaterfallMC/Waterfall-Old#52]
Any nicer way to output this exception when a user can't authenticate through mojang servers?

Waterfall dev 186

```
04:00:16 [SEVERE] Error authenticating [user] with minecraft.net
java.net.UnknownHostException: sessionserver.mojang.com
    at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
    at java.net.InetAddress.getAllByName(InetAddress.java:1192)
    at java.net.InetAddress.getAllByName(InetAddress.java:1126)
    at java.net.InetAddress.getByName(InetAddress.java:1076)
    at net.md_5.bungee.http.HttpClient.get(HttpClient.java:64)
    at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:458)
    at net.md_5.bungee.protocol.packet.EncryptionResponse.handle(EncryptionResponse.java:49)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.fireChannelRead(DirectByteToMessageDecoder.java:179)
    at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.channelRead(DirectByteToMessageDecoder.java:169)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by kamcio96** [comment]
it's common when mojang change their login server, just ignore :wink:
