### ISSUE TITLE
Can't join server

### ISSUE THREAD

**Issue by ghost** [WaterfallMC/Waterfall-Old#64]
Null exception while joining the server:
http://pastebin.com/raw/aaBTsCbf

When I join the server by any chance I get kicked very fast with the same error.

**Comment by camdenorrb** [comment]
Can verify, same thing is happening to me :C

**Comment by Janmm14** [comment]
## FastIntern is broken partly

The first time any string gets interned, `existing` is `null` at this point: [FastIntern:25](https://github.com/WaterfallMC/Waterfall/commit/43e447a262a257f6ab2f43208abd645eda1c8bd3#diff-a6b96c2c7b4f4bf464b7ba318905ced8R25)

This is due to the `putIfAbsent` method returns the previously associated value to the key if the map did not contained that key, which is always `null` in this case. (See javadocs)

**Comment by ghost** [comment]
So? Shouldn't you fix this?

**Comment by Janmm14** [comment]
@CzlowiekKuktas You might think that I would work for Waterfall, but I am just pointing to issues that the maintainers of Waterfall should fix to help them out.

I have my own modif[i](https://github.com/minotopiame/flexpipe)ed BungeeCord project. (I want to give sth. back as I sometimes just copy their code, still credited, but).

**Comment by ghost** [comment]
I don't really care, I just want Waterfall to work.

**Comment by mibby** [comment]
@CzlowiekKuktas Haha, polite much? Maybe try reaching out in the waterfall IRC channel.

**Comment by ghost** [comment]
Sorry, if I'm not polite enough. English is not my first language, buy they are just releasing bugged version of the project without any help.

**Comment by Janmm14** [comment]
@CzlowiekKuktas Use an older version instead then.

**Comment by ghost** [comment]
I'm using, but I want to edit the source code, which is broken.

**Comment by mibby** [comment]
Pasting the full stacktrace on github in case the pastebin link goes down.

WaterFall dev 199

```
16:05:51 [SEVERE] [/IP:PORT|PLAYER] <-> DownstreamBridge <-> [EosCraft] - encountered exception
java.lang.NullPointerException
    at io.github.waterfallmc.waterfall.utils.FastIntern.intern(FastIntern.java:26)
    at net.md_5.bungee.api.score.Team.addPlayer(Team.java:34)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:211)
    at net.md_5.bungee.protocol.packet.Team.handle(Team.java:110)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.fireChannelRead(DirectByteToMessageDecoder.java:179)
    at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.channelRead(DirectByteToMessageDecoder.java:169)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
16:05:51 [INFO] [PLAYER] disconnected with: §fNullPointerException : null @ io.github.waterfallmc.waterfall.utils.FastIntern:26
```

@CzlowiekKuktas I recommend just downgrading to build 193 for now until the problem gets resolved.

**Comment by ghost** [comment]
I'm using, but I want to edit the source code, which is broken.

**Comment by Janmm14** [comment]
@CzlowiekKuktas You can use git to get an older version of the source code. You can use google for further information about git and how to use it.

**Comment by ghost** [comment]
How to use it?
