### ISSUE TITLE
1.9.4 support?

### ISSUE THREAD

**Issue by Leymooo** [WaterfallMC/Waterfall-Old#72]
title

**Comment by Janmm14** [comment]
Wait until the developers have time and they'll update.

**Comment by ConnorLinfoot** [comment]
1.9.3/1.9.4 build courtesy of @Tim-NL (https://github.com/Tim-NL/Waterfall)

https://connorlinfoot.com/waterfall.jar

**Comment by Tim-NL** [comment]
Lol does that work? I'have just added the new protocol but didn't test :3

**Comment by ConnorLinfoot** [comment]
Seems to be working for me, was going to update it myself but noticed you forked it and so far so good :)

**Comment by dyanakiev** [comment]
1.9.4? ?? ? ?? ? ?

**Comment by Tim-NL** [comment]
1.9.3 & 1.9.4 is the same protocol version.

**Comment by minecrafter** [comment]
I'm working on properly merging 1.9.4 support now.

**Comment by punkeel** [comment]
Done, am I right?

**Comment by minecrafter** [comment]
Yes

**Comment by minecrafter** [comment]
1.9.x support seems broken. <=1.8 should work fine, however. Investigating.

**Comment by mibby** [comment]
@minecrafter I'm assuming 1.9.4 support hasn't been merged into the repo yet, unless there is another issue with Waterfall 1.9.4? BungeeCord dev 1152 is fine.

Waterfall dev 210
![link](http://i.imgur.com/GvPH0H5.png)

```
21:14:43 [WARNING] [/IP:PORT|PLAYER] <-> DownstreamBridge <-> [server] - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Respawn 7 Protocol GAME Direction net.md_5.bungee.protocol.Protocol$DirectionData@8a0f431
21:14:43 [INFO] [PLAYER] disconnected with: §fDecoderException : net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Respawn 7 Protocol GAME Direction net.md_5.bungee.protocol.Protocol$DirectionData@8a0f431 @ io.netty.handler.codec.MessageToMessageDecoder:99
```

```
21:14:54 [SEVERE] [/IP:PORT|PLAYER] <-> DownstreamBridge <-> [SERVER] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(101) exceeds writerIndex(52): SlicedAbstractByteBuf(ridx: 8, widx: 52, cap: 52/52, unwrapped: PooledUnsafeDirectByteBuf(ridx: 53, widx: 102, cap: 512))
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.fireChannelRead(DirectByteToMessageDecoder.java:179)
    at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.callDecode(DirectByteToMessageDecoder.java:266)
    at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.channelRead(DirectByteToMessageDecoder.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(101) exceeds writerIndex(52): SlicedAbstractByteBuf(ridx: 8, widx: 52, cap: 52/52, unwrapped: PooledUnsafeDirectByteBuf(ridx: 53, widx: 102, cap: 512))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1178)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1172)
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:693)
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:701)
    at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:30)
    at net.md_5.bungee.protocol.packet.Respawn.read(Respawn.java:29)
    at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:204)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:37)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    ... 16 more
21:14:54 [INFO] [PLAYER] disconnected with: §fDecoderException : java.lang.IndexOutOfBoundsException: readerIndex(8) + length(101) exceeds writerIndex(52): SlicedAbstractByteBuf(ridx: 8, widx: 52, cap: 52/52, unwrapped: PooledUnsafeDirectByteBuf(ridx: 53, widx: 102, cap: 512)) @ io.netty.handler.codec.MessageToMessageDecoder:99
```

**Comment by minecrafter** [comment]
@mibby I found why. Fix should be coming soon...
